name: Cleanup Duplicate Team Images Across Folders

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: حذف الصور المكررة من مجلدات الفرق
        run: |
          for dir in teams-imgs national-teams-imgs; do
            if [[ -d "$dir" ]]; then
              echo "🧹 تنظيف المجلد: $dir"
              cd "$dir"
              for file in *; do
                if [[ -f "$file" ]]; then
                  id=$(echo "$file" | sed -E 's/^([0-9]+).*$/\1/')
                  original="$id.${file##*.}"
                  if [[ "$file" != "$original" && -f "$original" ]]; then
                    echo "🗑 حذف: $file (المجلد: $dir، الأصل: $original)"
                    rm "$file"
                  fi
                fi
              done
              cd ..
            else
              echo "⚠️ المجلد غير موجود: $dir"
            fi
          done

      - name: حفظ التغييرات
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "حذف الصور المكررة حسب المعرف من مجلدات الفرق" || echo "لا تغييرات للحفظ"
          git push
